services:
  - type: web
    name: minusu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "false"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_SENDER
        sync: false
      - key: MAIL_RECEIVER
        sync: false
